// @noref[scripts/src/linguist/gen-extensions.mjs, languages.yml]
import assert from "node:assert/strict";
import { test } from "node:test";

import { extractExtensions, render } from "../../src/linguist/gen-extensions.mjs";

/// A `languages.yml` slice with the shapes the parser has to tell apart.
const YAML = `Ruby:
  type: programming
  extensions:
  - ".rb"
  - ".RBW"
  filenames:
  - Rakefile
  interpreters:
  - ruby
Text:
  type: prose
  extensions:
  - ".txt"
  - ".d.ts"
  - ".2"
  - ".café"
  - ".TXT"
`;

test("extensions are lowercased, stripped of the leading dot, and deduplicated", () => {
  const { sorted } = extractExtensions(YAML, 1);
  assert.ok(sorted.includes("rb"));
  assert.ok(sorted.includes("rbw"), "uppercase entries are folded down");
  assert.equal(sorted.filter((e) => e === "txt").length, 1, "duplicates collapse");
});

// Sibling lists sit at the same indentation as the extension items, so absorbing them would
// silently poison the table with filenames and interpreter names.
test("sibling lists are not absorbed into the extension list", () => {
  const { sorted } = extractExtensions(YAML, 1);
  assert.ok(!sorted.includes("rakefile"));
  assert.ok(!sorted.includes("ruby"));
});

test("multi-dot, all-digit and non-ascii entries are dropped and counted", () => {
  const { sorted, dropped } = extractExtensions(YAML, 1);
  assert.ok(!sorted.includes("d.ts"));
  assert.ok(!sorted.includes("2"));
  assert.ok(!sorted.includes("café"));
  assert.equal(dropped.multiDot, 1);
  assert.equal(dropped.allDigit, 1);
  assert.equal(dropped.nonAscii, 1);
});

// The generated table is searched with `binary_search`, which requires Rust's byte ordering.
test("entries are sorted in byte order so binary_search holds", () => {
  const { sorted } = extractExtensions(YAML, 1);
  const byBytes = [...sorted].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  assert.deepEqual(sorted, byBytes);
});

test("a layout change that yields too few entries is an error, not a silent truncation", () => {
  assert.throws(
    () => extractExtensions("Ruby:\n  extensions:\n  - \".rb\"\n", 1000),
    /only 1 extensions/,
  );
});

test("the rendered table names its generator and pinned source", () => {
  const output = render({ sorted: ["rb", "txt"], dropped: { multiDot: 0, nonAscii: 0, allDigit: 0 } }, "abc123");
  assert.match(output, /Generated by @ref\[scripts\/src\/linguist\/gen-extensions\.mjs\]/);
  assert.match(output, /abc123/);
  assert.match(output, /"rb",/);
  assert.match(output, /fn is_linguist_extension/);
  assert.ok(output.endsWith("\n"));
});
