//! `anchr coverage` and `anchr annotate` against fixture repositories.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::fs;

use assert_cmd::Command;
use predicates::prelude::*;

struct Fixture {
    _dir: tempfile::TempDir,
    root: std::path::PathBuf,
}

impl Fixture {
    fn new(files: &[(&str, &str)]) -> Self {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("repo");
        for (path, contents) in files {
            let full = root.join(path);
            fs::create_dir_all(full.parent().unwrap()).unwrap();
            fs::write(full, contents).unwrap();
        }
        Self { _dir: dir, root }
    }

    fn anchr(&self) -> Command {
        let mut command = Command::cargo_bin("anchr").unwrap();
        command.current_dir(&self.root);
        command
    }

    fn read(&self, path: &str) -> String {
        fs::read_to_string(self.root.join(path)).unwrap()
    }
}

fn fixture() -> Fixture {
    Fixture::new(&[
        (
            "README.md",
            "See `docs/guide.md` and docs/missing.md; call `run_check`. Already @ref[docs/guide.md].\n",
        ),
        ("docs/guide.md", "# Guide\n"),
        ("src/lib.rs", "pub fn run_check() {}\n"),
    ])
}

#[test]
fn coverage_reports_candidates_and_never_fails() {
    let fixture = fixture();
    fixture
        .anchr()
        .args(["coverage", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains(
            "`docs/guide.md` — could be @ref[docs/guide.md]\n --> README.md:1:5\n",
        ))
        .stdout(predicate::str::contains(
            "`docs/missing.md` — does not resolve",
        ))
        .stdout(predicate::str::contains("run_check").not())
        .stdout(predicate::str::contains(
            "1 of 3 reference-shaped strings are annotated; 1 could be, 1 do not resolve",
        ));

    let output = fixture
        .anchr()
        .args(["coverage", "--format", "json"])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(json["schema"], 1);
    assert_eq!(json["summary"]["total"], 3);
    assert_eq!(json["summary"]["proposals"], 1);
    let candidates = json["candidates"].as_array().unwrap();
    assert_eq!(candidates.len(), 2);
    assert_eq!(candidates[0]["kind"], "proposal");
    assert_eq!(candidates[0]["text"], "docs/guide.md");
    assert_eq!(candidates[0]["count"], 1);
    assert_eq!(candidates[0]["sites"][0]["region"], "inline-code");
    assert_eq!(candidates[0]["sites"][0]["text"], "`docs/guide.md`");
    assert!(candidates[0].get("location").is_none());
    assert_eq!(candidates[1]["kind"], "unresolvable");
}

#[test]
fn sites_of_one_token_are_grouped_and_capped() {
    let mut files: Vec<(String, String)> = (0..45)
        .map(|n| {
            (
                format!("src/gen{n:02}.rs"),
                "// Generated by gen.js\n".to_owned(),
            )
        })
        .collect();
    files.push(("README.md".to_owned(), "See gen.js.\n".to_owned()));
    let borrowed: Vec<(&str, &str)> = files
        .iter()
        .map(|(path, text)| (path.as_str(), text.as_str()))
        .collect();
    let fixture = Fixture::new(&borrowed);
    let output = fixture
        .anchr()
        .args(["coverage", "--color", "never"])
        .output()
        .unwrap();
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.starts_with("`gen.js` — does not resolve: missing path `gen.js` in root `repo`\n --> README.md:1:5\n --> src/gen00.rs:1:17\n"), "{stdout}");
    assert_eq!(stdout.matches(" --> ").count(), 40);
    assert!(stdout.contains(" = note: and 6 more sites\n\n0 of 46 reference-shaped strings are annotated; 0 could be, 46 do not resolve\n"));

    let output = fixture
        .anchr()
        .args(["coverage", "--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    let candidates = json["candidates"].as_array().unwrap();
    assert_eq!(candidates.len(), 1);
    assert_eq!(candidates[0]["count"], 46);
    assert_eq!(candidates[0]["sites"].as_array().unwrap().len(), 46);
}

#[test]
fn alias_words_are_proposed_and_unused_aliases_are_listed() {
    let fixture = Fixture::new(&[
        (
            "docs/a.md",
            "@ref[docs/guide.md as Guide] @ref[docs/guide.md as Spare]\nRead the Guide and `Guide`. @[Guide].\n",
        ),
        ("docs/guide.md", "# Guide\n"),
    ]);
    fixture
        .anchr()
        .args(["coverage", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains(
            "`Guide` — could be @[Guide]\n --> docs/a.md:2:10\n --> docs/a.md:2:20\n",
        ))
        .stdout(predicate::str::contains(
            "`Spare` — alias declared but never used\n --> docs/a.md:1:52\n",
        ))
        .stdout(predicate::str::contains(
            "3 of 5 reference-shaped strings are annotated; 2 could be, 0 do not resolve; 1 alias is declared but never used",
        ));

    let output = fixture
        .anchr()
        .args(["coverage", "--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(json["summary"]["unused_aliases"], 1);
    let candidates = json["candidates"].as_array().unwrap();
    let kinds: Vec<&str> = candidates
        .iter()
        .map(|c| c["kind"].as_str().unwrap())
        .collect();
    assert_eq!(kinds, vec!["proposal", "unused-alias"]);
    assert_eq!(candidates[0]["count"], 2);
    let texts: Vec<&str> = candidates[0]["sites"]
        .as_array()
        .unwrap()
        .iter()
        .map(|site| site["text"].as_str().unwrap())
        .collect();
    assert_eq!(texts, vec!["Guide", "`Guide`"]);

    fixture
        .anchr()
        .args(["annotate", "--write", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains("annotated 2 references"));
    assert_eq!(
        fixture.read("docs/a.md"),
        "@ref[docs/guide.md as Guide] @ref[docs/guide.md as Spare]\nRead the @[Guide] and @[Guide]. @[Guide].\n"
    );
    fixture
        .anchr()
        .args(["check", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains(
            "checked 2 references and 3 alias uses in 2 files",
        ));
}

#[test]
fn ignores_suppress_candidates_and_unused_entries_are_reported() {
    let fixture = Fixture::new(&[
        (
            "anchr.toml",
            "[coverage]\nexclude = [\"archive/**\"]\nignore = [\"CLAUDE.md\", \"never.md\"]\n",
        ),
        (
            "docs/a.md",
            "@noref[foo.ts, spare.md]\nSee `docs/guide.md`, foo.ts, and CLAUDE.md. @ref[docs/guide.md]\n",
        ),
        ("archive/old.md", "docs/guide.md\n"),
        ("docs/guide.md", "# Guide\n"),
    ]);
    fixture
        .anchr()
        .args(["coverage", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains(
            "`docs/guide.md` — could be @ref[docs/guide.md]\n --> docs/a.md:2:5\n",
        ))
        .stdout(predicate::str::contains(
            "`spare.md` — ignored but never matched\n --> docs/a.md:1:16\n",
        ))
        .stdout(predicate::str::contains(
            "`never.md` — ignored but never matched\n --> anchr.toml\n",
        ))
        .stdout(predicate::str::contains("archive/old.md").not())
        .stdout(predicate::str::contains(
            "1 of 2 reference-shaped strings are annotated; 1 could be, 0 do not resolve; 2 strings ignored; 2 ignore entries never matched",
        ));

    let output = fixture
        .anchr()
        .args(["coverage", "--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(json["summary"]["ignored"], 2);
    assert_eq!(json["summary"]["unused_ignores"], 2);
    assert_eq!(
        json["unused_config_ignores"],
        serde_json::json!(["never.md"])
    );
    let kinds: Vec<&str> = json["candidates"]
        .as_array()
        .unwrap()
        .iter()
        .map(|c| c["kind"].as_str().unwrap())
        .collect();
    assert_eq!(kinds, vec!["proposal", "unused-ignore"]);

    fixture
        .anchr()
        .args(["annotate", "--write", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains("annotated 1 reference"));
    assert_eq!(
        fixture.read("docs/a.md"),
        "@noref[foo.ts, spare.md]\nSee @ref[docs/guide.md], foo.ts, and CLAUDE.md. @ref[docs/guide.md]\n"
    );
    fixture
        .anchr()
        .args(["check", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains("checked 2 references"));
}

#[test]
fn a_malformed_noref_list_is_a_check_error() {
    let fixture = Fixture::new(&[("docs/a.md", "@noref[a,]\n")]);
    fixture
        .anchr()
        .args(["check", "--color", "never"])
        .assert()
        .code(1)
        .stdout(predicate::str::contains("@noref"))
        .stdout(predicate::str::contains("invalid ignore list `a,`"));
}

#[test]
fn annotate_only_writes_with_the_flag_and_the_result_passes_check() {
    let fixture = fixture();
    fixture
        .anchr()
        .args(["annotate", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains(
            "README.md:1:5: `docs/guide.md` -> @ref[docs/guide.md]",
        ))
        .stdout(predicate::str::contains(
            "1 proposal; pass --write to apply",
        ));
    assert!(fixture.read("README.md").contains("`docs/guide.md`"));

    fixture
        .anchr()
        .args(["annotate", "--write", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains("edited README.md"))
        .stdout(predicate::str::contains("annotated 1 reference"));
    assert_eq!(
        fixture.read("README.md"),
        "See @ref[docs/guide.md] and docs/missing.md; call `run_check`. Already @ref[docs/guide.md].\n"
    );

    fixture
        .anchr()
        .args(["check", "--color", "never"])
        .assert()
        .code(0);

    fixture
        .anchr()
        .args(["coverage", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains(
            "2 of 3 reference-shaped strings are annotated",
        ));
}

#[test]
fn directory_globs_are_proposed_as_directories_and_annotate_writes_them() {
    let fixture = Fixture::new(&[
        ("README.md", "Sources live in `src/*`; docs in docs/.\n"),
        ("src/lib.rs", ""),
        ("docs/a.md", ""),
    ]);
    fixture
        .anchr()
        .args(["coverage", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains(
            "`src/*` — could be @ref[src/]\n --> README.md:1:17\n",
        ))
        .stdout(predicate::str::contains("`docs/` — could be @ref[docs/]"));

    let output = fixture
        .anchr()
        .args(["coverage", "--format", "json"])
        .output()
        .unwrap();
    let json: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    let candidates = json["candidates"].as_array().unwrap();
    assert_eq!(candidates.len(), 2);
    assert_eq!(candidates[0]["text"], "docs/");
    assert_eq!(candidates[1]["text"], "src/*");
    assert_eq!(candidates[1]["replacement"], "@ref[src/]");
    assert_eq!(candidates[1]["sites"][0]["text"], "`src/*`");

    fixture
        .anchr()
        .args(["annotate", "--write", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains("annotated 2 references"));
    assert_eq!(
        fixture.read("README.md"),
        "Sources live in @ref[src/]; docs in @ref[docs/].\n"
    );
    fixture
        .anchr()
        .args(["check", "--color", "never"])
        .assert()
        .code(0);
}

#[test]
fn prose_word_pairs_are_not_reference_shaped() {
    let fixture = Fixture::new(&[(
        "README.md",
        "Reports line/col; licensed Apache-2.0/MIT, e.g. since 1.x, i.e. never `struct/class`.\n",
    )]);
    let output = fixture
        .anchr()
        .args(["coverage", "--format", "json"])
        .output()
        .unwrap();
    assert_eq!(output.status.code(), Some(0));
    let json: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(json["summary"]["total"], 0);
    assert_eq!(json["candidates"].as_array().unwrap().len(), 0);
    for key in [
        "annotated_refs",
        "total",
        "proposals",
        "unresolvable",
        "unused_aliases",
        "ignored",
        "unused_ignores",
    ] {
        assert!(json["summary"].get(key).is_some(), "{key}");
    }
}

#[test]
fn file_relative_proposals_are_written_by_annotate_and_pass_check() {
    let fixture = Fixture::new(&[
        ("docs/README.md", "See guide.md and lost.md.\n"),
        ("docs/guide.md", "# Guide\n"),
        ("other/lost.md", ""),
    ]);
    fixture
        .anchr()
        .args(["coverage", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains(
            "`guide.md` — could be @ref[./guide.md]\n --> docs/README.md:1:5\n",
        ))
        .stdout(predicate::str::contains(
            "`lost.md` — does not resolve: missing path `lost.md` in root `repo`; one file named `lost.md` exists at `other/lost.md`\n",
        ));
    fixture
        .anchr()
        .args(["annotate", "--write", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains("annotated 1 reference"));
    assert_eq!(
        fixture.read("docs/README.md"),
        "See @ref[./guide.md] and lost.md.\n"
    );
    fixture
        .anchr()
        .args(["check", "--color", "never"])
        .assert()
        .code(0)
        .stdout(predicate::str::contains("1 resolved, 0 errors"));
}
